name: Test CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  jest-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MySQL
        run: |
          sudo apt update
          sudo apt install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql

      - name: Wait for MySQL to Be Ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {30..0}; do
            if sudo mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL not ready yet. Retrying in 2 seconds..."
            sleep 2
          done
          if [ "$i" = 0 ]; then
            echo "MySQL did not start in time."
            exit 1
          fi

      - name: Set up MySQL
        run: |
          echo "Updating MySQL authentication..."
          sudo mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.DB_ROOT_PASSWORD }}';"
          sudo mysql -uroot -p${{ secrets.DB_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"
          
          echo "Creating Database and User..."
          sudo mysql -uroot -p${{ secrets.DB_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
          sudo mysql -uroot -p${{ secrets.DB_ROOT_PASSWORD }} -e "CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
          sudo mysql -uroot -p${{ secrets.DB_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ secrets.DB_USER }}'@'localhost';"
          sudo mysql -uroot -p${{ secrets.DB_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"

          echo "Restarting MySQL..."
          sudo systemctl restart mysql

      - name: Configure Environment Variables
        run: |
          echo "Writing environment variables to .env file..."
          touch src/.env
          echo DB_Host=${{ secrets.DB_HOST }} >> src/.env
          echo DB_User=${{ secrets.DB_USER }} >> src/.env
          echo DB_Pass=${{ secrets.DB_PASSWORD }} >> src/.env
          echo DB_Name=${{ secrets.DB_NAME }} >> src/.env
          echo DB_Port=${{ secrets.DB_PORT || '3306' }} >> src/.env  # Default to 3306 if not set

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        working-directory: src

      - name: Run Tests
        run: npm test
        working-directory: src