name: Node.js-Test

on:
    pull_request:
      branches: [ "main" ]
    push:
      branches: [ "main" ]

jobs:
  jest-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MySQL
        run: |
          sudo apt update
          sudo apt install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql

      - name: Configure MySQL
        run: |
          echo "Creating MySQL user and database..."
          sudo mysql -u root -h 127.0.0.1 <<EOF
          CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';
          CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};
          GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ secrets.DB_USER }}'@'%';
          FLUSH PRIVILEGES;
          EOF
          sudo systemctl restart mysql

      - name: Configure Environment Variables
        run: |
          echo "Writing environment variables to src/.env file..."
          touch src/.env
          echo DB_Host=127.0.0.1 >> src/.env
          echo DB_User=${{ secrets.DB_USER }} >> src/.env
          echo DB_Pass=${{ secrets.DB_PASSWORD }} >> src/.env
          echo DB_Name=${{ secrets.DB_NAME }} >> src/.env
          echo DB_Port=${{ secrets.DB_PORT || '3306' }} >> src/.env
          echo APP_Port=${{ secrets.PORT }} >> src/.env
          echo DB_SSLMode=${{ secrets.DB_SSLMODE }} >> src/.env
          echo S3_Bucket=abc >> src/.env
          echo Bucket_Name=1234 >> src/.env

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd src
          npm install

      - name: Run Tests
        run: |
          cd src
          export $(grep -v '^#' .env | xargs)  # Load environment variables
          npm test
