name: Packer CI

on:
  pull_request:
    branches: [main]

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.12.0'

      - name: Check Packer format
        working-directory: src/packer
        run: |
          packer fmt -check .

      - name: Initialize Packer template
        working-directory: src/packer
        run: |
          packer init .

      - name: Validate Packer template
        working-directory: src/packer
        run: |
          packer validate .
